name: Publish to Sonatype
on:
  push:
    tags: ["*"]

jobs:
  publish:
    uses: arturopala/workflows/.github/workflows/publish.yml@main
    secrets:
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      PGP_SECRET: ${{ secrets.PGP_SECRET }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}