name: Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --tags --unshallow -f  
      - name: Setup scala
        uses: olafurpg/setup-scala@v10
      - name: Generate documentation
        run: sbt docs/mdoc 
      - name: Commit documentation changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Artur Opala
          author_email: opala.artur@gmail.com
          message: 'Update documentation'
          add: '*.md'
      - name: Compute and set release tag
        id: compute_tag
        uses: craig-day/compute-tag@v11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version_scheme: semantic
          version_type: minor    
          branch: master
      - name: Release to Sonatype
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: Generate release changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.compute_tag.outputs.next_tag }}
          release_name: ${{ steps.compute_tag.outputs.next_tag }}
          body: |
            Release ${{ steps.compute_tag.outputs.next_tag }}

            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: Push site to gh-pages
        run: sbt ghpagesPushSite    
    