name: Site
on:
  workflow_dispatch:

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup scala
        uses: olafurpg/setup-scala@v10
      - name: Generate README
        run: sbt docs/mdoc 
      - name: Commit README changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Artur Opala
          author_email: opala.artur@gmail.com
          message: 'Update README'
          add: '*.md'    
      - name: Publish API documentation on Github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "> Publish GitHub Pages"
          sbt makeSite publishToGitHubPages   
    